---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: run kibana centos 7
    shell: /etc/rc.d/init.d/kibana start
    when: ansible_facts.pkg_mgr == 'yum'

  - name: Kibana test web
    retries: 30
    shell: curl http://127.0.0.1:5601
    register: web_kibana
    until: web_kibana is succeeded 
 
